import React, {useRef, useEffect} from 'react'
import Head from 'next/head'
import gsap from 'gsap'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {


  const boxRef = useRef();

  // wait until DOM has been rendered
  useEffect(() => {
    gsap.to(boxRef.current, { rotation: "+=360" });
  });


  return (
    <div className={styles.container}>
      <Head>
        <title>Sergey Bocharov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <figure className={styles.user}>
          <img src="/sergeybocharov.jpg" alt="Sergey Bocharov" />
        </figure>
        <h1 className={styles.title}>
        Hi. I'm  <a  target="_blank" href="https://www.linkedin.com/in/bocharovsergey">Sergey Bocharov</a>
        </h1>

        <div  className="box" ref={boxRef}>Hello</div>

        <p className={styles.description}>
          I’m a Frontend Team Lead at <Link href='https://www.sberbank.com/index'><a>Sber</a></Link>.{<br/>}
          I'm especially interested in <code className={styles.code}>JS</code>, <code className={styles.code}>Node.js</code> and <code className={styles.code}>Python</code>.
          {<br/>}
          I speak at CONFERENCES and make VIDEOS.{<br/>}
        </p>


        <p className={styles.Box} >I make digital (and magical) ...
          {/* <Counter/> */}
        </p>

        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
          <h2>About &rarr;</h2>
            <p>Find more information about me.</p>
          </a>

          <a href="#" className={styles.card}>
          <h2>Projects &rarr;</h2>
            <p>Learn more about my projects on CodePen or GitHub!</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Writing &rarr;</h2>
            <p>Sometimes I write for Smashing Magazine, Medium, and others. My writing on this site is mostly personal.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Speeking &rarr;</h2>
            <p>
            These are conferences I will or have spoken at, as well as summaries of the talks I’ve given.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      <p>
        Follow me on &nbsp;<Link href="https://codepen.io/ibemed" rel="noopener noreferrer" target="_blank" ><a><img alt="CodePen" src="/CodePen.svg" />&nbsp; CodePen</a></Link> &nbsp; or &nbsp; <Link href="https://github.com/godfreyd" rel="noopener noreferrer" target="_blank"><a><img alt="GitHub" src="/GitHub.svg" />&nbsp;GitHub</a></Link>&nbsp; if you want, I suppose.
        </p>
      </footer>
    </div>
  )
}
